name: brontosaurus_flutter
description: ":iphone: Flutter package for Brontosaurus"
version: 0.1.0
author: WMXPY
homepage: https://github.com/SudoDotDog/Brontosaurus-Flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^0.3.18+1

dev_dependencies:
  flutter_test:
    sdk: flutter
